INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (1,'GREAT','TERRIBLE','Worth it!');
INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (2,'GREAT','TERROR', 'Very respectable company');
INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (3,'NICE','Very Overrated', 'Life-changing experience');
INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (4,'OUTSTANDING','N/A', 'Greatest decision made!');
INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (5,'NICE','Not everyone''s cup of tea', 'Don''t bother, look for something else');
INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (6,'PERFECT PLACE','Did not get full-time afterwards', 'Best place to be in');
INSERT INTO REVIEW (COMPANY_ID, GOOD_REVIEW, BAD_REVIEW, RECENT_REVIEW) VALUES (7,'Heaven on earth place','God-Awful experience', 'It is what it is');