INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Amazon', 'FAANG');
INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Microsoft', 'FAANG');
INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Facebook', 'FAANG');
INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Dropbox','Mid-sized');
INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Capital One','Non-traditional');
INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Cisco', 'Network');
INSERT INTO COMPANY (COMPANY_NAME, COMPANY_TYPE) VALUES ('Figma', 'Start-up');